sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t beuelvinc/elvins-app -f ./client/Dockerfile.dev ./client

script:
  - docker run  -e CI=TRUE beuelvinc/elvins-app  npm test

after_success:
  - docker build -t beuelvinc/multi-client -f ./client/Dockerfile.dev ./client
  - docker build -t beuelvinc/multi-nginx -f ./nginx/Dockerfile.dev ./nginx
  - docker build -t beuelvinc/multi-server -f ./server/Dockerfile.dev ./server
  - docker build -t beuelvinc/multi-worker -f ./worker/Dockerfile.dev ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push beuelvinc/multi-client
  - docker push beuelvinc/multi-nginx
  - docker push beuelvinc/multi-server
  - docker push beuelvinc/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"  # take from url
  app: "multi" # same as in aws
  env: "Multi-env" #same as in aws
  bucket_name: "elasticbeanstalk-us-east-1-250932413033" # same as in aws
  bucket_path: "multi" # changes after u deploy/first it is app name
  on:
    branch: main #main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY